package com.osrsGoalTracker.orchestration.events;

import java.time.Instant;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

import lombok.Builder;
import lombok.Value;

/**
 * Event published when a goal is requested to be created.
 * Contains all necessary information to create a goal and set its initial
 * progress.
 */
@Value
@Builder
@JsonDeserialize(builder = GoalCreationRequestEvent.GoalCreationRequestEventBuilder.class)
public class GoalCreationRequestEvent {
    /**
     * The ID of the user who owns this goal.
     */
    private final String userId;

    /**
     * The name of the character this goal is for.
     */
    private final String characterName;

    /**
     * The name of the skill or activity (e.g., "WOODCUTTING", "BOUNTY_HUNTER").
     */
    private final String targetAttribute;

    /**
     * The type of goal (e.g., SKILL, ACTIVITY).
     */
    private final String targetType;

    /**
     * The target value to achieve.
     */
    private final long targetValue;

    /**
     * The current value towards the goal.
     */
    private final long currentValue;

    /**
     * The deadline for this goal.
     */
    private final Instant targetDate;

    /**
     * The notification channel type (e.g., DISCORD, EMAIL).
     */
    private final String notificationChannelType;

    /**
     * The frequency of notifications (e.g., DAILY, WEEKLY, MONTHLY).
     */
    private final String frequency;

    /**
     * Builder for GoalCreationRequestEvent.
     */
    @JsonPOJOBuilder(withPrefix = "")
    public static class GoalCreationRequestEventBuilder {
        // Builder will be generated by Lombok
    }
}
